// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/Walk.tsx";
import * as $$1 from "./islands/WalkDeno.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/Walk.tsx": $$0,
    "./islands/WalkDeno.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
